### ISSUE TITLE
Unable to launch game from terminal on Linux

### ISSUE THREAD

**Issue by GenesisGreen** [ActualMandM/Doki-Doki-Takeover-BAD-ENDING#2]
When I try launching the game using the terminal on Linux, I get this:
./DokiTakeoverBadEnding: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./DokiTakeoverBadEnding)
./DokiTakeoverBadEnding: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./DokiTakeoverBadEnding)
I'm assuming I have to install GLIBC, however I'm not sure how to.

**Comment by RagdollClash** [comment]
What distro of Linux is it? Can check with something like `neofetch`.

**Comment by GenesisGreen** [comment]
> What distro of Linux is it? Can check with something like `neofetch`.

Linux Mint 20.3

**Comment by RagdollClash** [comment]
I'm unsure how to update libc... what happens if you try building the mod from source?

**Comment by GenesisGreen** [comment]
Seems to work perfectly when built from source code!
Wonder why the pre-compiled version didn't work however.
Thank you for responding!

**Comment by RagdollClash** [comment]
This issue also happens on the Steam Deck, gonna try Psych's GitHub workflow to see if its compilation fixes the issue

**Comment by RagdollClash** [comment]
@GenesisGreen are you able to check to see if the workflow version boots up just fine for you?
