### ISSUE TITLE
Bug Report: Low Quality Crashing

### ISSUE THREAD

**Issue by SomeRandomDylan** [ActualMandM/Doki-Doki-Takeover-BAD-ENDING#3]
During the first transition in HOME, the game crashes if the player has low quality mode enabled.

On the first release of the unfair update, it threw this error:
![image_2023-12-24_182108243](https://github.com/ActualMandM/Doki-Doki-Takeover-BAD-ENDING/assets/88756159/716caa31-4f92-48b2-87d2-6bfb5965deb3)

And on the current commit, it either crashes with a memory error or with no error box at all.

**Comment by RagdollClash** [comment]
Fixed, will be in the upcoming update.
